travis:
  secure:
    BINSTAR_TOKEN: RXlqJnU42Ko5Bvab0bgW2NuAgCo2JzhVokANOfBHMcUaf1eaAEHPNPj8rCDPfG4yNihDaCIu1bne9kWICZ1C1QuhjNEN94vNVaff6kidTtXoCS4IULY67c3fdgWhMI3L2dcsnPryz156lH8Cxw2oCKjc3RlI1tKiZKOL0wOJ9Xn2s6rtYiEXB6LPIk4fn+5xH1mNfEvZiQ8j5Bd8axt33p6ff4SVYsmjIRjzrjVayJyK3AHa4dfx5DMpgmV/C9whF/hzrtr64H4q0NScUs2k7NCluwJ9zybmokxRhKmj4vDTFYN1q5Ez+EPjtsQGDXxkaA8MXv33ZH5arUvXd/6MvcoclENdDIQfwj6oifYLGbvprOcSwoV/pXav/4U5tSysFVCACKW5jaeHREOCfhuzve2bNw5uVWQpE7VgHXMN3dUETYwmlWiI8gD3pmn2M7PIY3DQh3wUw/Q6t7nBdnic7dPMcm/zPM9qZEHo6jjaQxPH3I0ds8fySDYnYKSRvFwBXQsWr9Y053C4n2TN9E7QykowoRcjbwu8JNMnMGtxOuJVFO4PiRBp0x4z/wwPG1Ghyy0snRoylz7xTj7/s9Bd+GoIr+xaQKwVT8FEHfGvLlXdlY77d2AHSPIpkkosggNIjDyBwnHBJngIGzr2qfVKVHuIpafARyzpw1LHfN4Wq5A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
